# Generated by Django 3.1.3 on 2021-04-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emmjoyusers',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emmjoyusers',
            name='is_tutor',
            field=models.BooleanField(default=False),
        ),
    ]
